import { StyleSheet } from "react-native";

export default function createStyles(colors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 32,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  eyebrow: {
    color: "#EF4444",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  title: {
    color: colors.text,
    fontSize: 32,
    fontWeight: "800",
  },
  headerIcon: {
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  hero: {
    height: 260,
    marginBottom: 18,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#111827",
  },
  heroImage: {
    flex: 1,
    justifyContent: "flex-end",
  },
  heroImageStyle: {
    opacity: 0.72,
  },
  heroOverlay: {
    padding: 18,
    backgroundColor: "rgba(17, 24, 39, 0.42)",
  },
  heroLabel: {
    marginBottom: 8,
    color: "#FCA5A5",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  heroTitle: {
    marginBottom: 8,
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
  },
  heroDescription: {
    marginBottom: 12,
    color: "#E5E7EB",
    fontSize: 14,
    lineHeight: 20,
  },
  heroMeta: {
    flexDirection: "row",
    gap: 8,
  },
  heroPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
  heroPillText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  statsGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  statCard: {
    flex: 1,
    minHeight: 94,
    justifyContent: "center",
    borderRadius: 8,
    padding: 12,
    backgroundColor: colors.surface,
  },
  statValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  statLabel: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },
  sectionHeader: {
    marginBottom: 12,
    marginTop: 2,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: "900",
  },
  categoryList: {
    gap: 12,
    paddingBottom: 20,
  },
  categoryCard: {
    width: 138,
    minHeight: 116,
    justifyContent: "space-between",
    borderRadius: 8,
    padding: 14,
    backgroundColor: colors.surface,
  },
  categoryName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  categoryTotal: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },
  watchList: {
    gap: 12,
    paddingBottom: 20,
  },
  watchCard: {
    width: 132,
  },
  watchPoster: {
    width: "100%",
    height: 178,
    borderRadius: 8,
    backgroundColor: colors.border,
  },
  watchTitle: {
    minHeight: 38,
    marginTop: 8,
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  progressTrack: {
    height: 5,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: colors.border,
  },
  progressFill: {
    height: "100%",
    borderRadius: 8,
    backgroundColor: "#EF4444",
  },
  card: {
    flexDirection: "row",
    marginBottom: 14,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: colors.surface,
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  poster: {
    width: 96,
    minHeight: 142,
    backgroundColor: colors.border,
  },
  info: {
    flex: 1,
    justifyContent: "center",
    padding: 14,
  },
  movieHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  movieTitle: {
    flex: 1,
    marginBottom: 6,
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  favoriteButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: colors.accentSoft,
  },
  movieMeta: {
    marginBottom: 12,
    color: colors.textSoft,
    fontSize: 14,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  badge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: colors.warningSoft,
    color: colors.warningText,
    fontSize: 13,
    fontWeight: "700",
  },
  duration: {
    color: colors.textSoft,
    fontSize: 13,
  },
  });
}
