import { StyleSheet } from "react-native";

export default function createStyles(colors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 34,
  },
  headerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 18,
    borderRadius: 8,
    padding: 16,
    backgroundColor: colors.surfaceStrong,
  },
  title: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
  },
  subtitle: {
    maxWidth: 230,
    marginTop: 6,
    color: "#D1D5DB",
    fontSize: 14,
    lineHeight: 19,
  },
  heartBadge: {
    alignItems: "center",
    justifyContent: "center",
    width: 54,
    height: 54,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  card: {
    flexDirection: "row",
    marginBottom: 14,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: colors.surface,
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  poster: {
    width: 102,
    minHeight: 160,
    backgroundColor: colors.border,
  },
  info: {
    flex: 1,
    padding: 14,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  movieTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  movieMeta: {
    marginTop: 6,
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  description: {
    marginTop: 10,
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 18,
  },
  badgeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: colors.surfaceAlt,
  },
  badgeText: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "800",
  },
  removeButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: colors.accentSoft,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 260,
    borderRadius: 8,
    padding: 24,
    backgroundColor: colors.surface,
  },
  emptyTitle: {
    marginTop: 12,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  emptyText: {
    maxWidth: 250,
    marginTop: 6,
    color: colors.textSoft,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  });
}
